add_newline = false
scan_timeout = 10

[character]
success_symbol = "[](#a3be8c)"
error_symbol = "[](#bf616a)"
vicmd_symbol = "[](#ebcb8b)"
format = "$symbol[Î» ](bold #67b0e8) "

[line_break]
disables = false
