---
update: true

system_packages:
  - linux-headers
  - base
  - base-devel
  - linux
  - linux-firmware
  - netctl
  - networkmanager
  - openssh

  - pipewire
  - pipewire-alsa
  - pipewire-audio
  - pipewire-pulse
  - pipewire-jack
  - pavucontrol
  - wireplumber

  - nvidia-open
  - libva-nvidia-driver
  - nvidia-utils
  - lib32-nvidia-utils
  - nvidia-settings
  - v4l2loopback-dkms
  - v4l2loopback-utils

  - egl-wayland

  - man-db
  - unzip
  - man-pages
  - reflector
  - mpv
  - mpv-mpris
  - git
  - wget
  - curl
  - udiskie
  - neovim
  - yazi

packages:
  - hyprland
  - cliphist
  - fuzzel
  - bemoji
  - waybar
  - xwaylandvideobridge
  - swww
  - dunst
  - polkit-kde-agent
  - qt5-wayland
  - qt6-wayland
  - xdg-desktop-portal-hyprland
  - xdg-desktop-portal-gtk
  - swappy
  - nwg-look

  - fd
  - tmux
  - fzf
  - ripgrep
  - zoxide
  - zsh
  - btop
  - starship
  - fastfetch
  - grimblast

  - gtk3
  - catppuccin-gtk-theme-mocha
  - apple_cursor
  - papirus-icon-theme
  - gnome-themes-extra

  - chaotic-aur/obs-studio-git

  - zoom
  - zathura
  - zathura-pdf-poppler
  - spotify
  # - steam
  # - chaotic-aur/vesktop-git
  # - librewolf
  - brave-bin
  - kitty
  - thunar
  - telegram
  # - zed
  - libreoffice-fresh

  - clang
  - python-pexpect

  - ttf-twemoji
  - ttf-jetbrains-mono-nerd
  - ttf-jetbrains-mono
  - ttf-nerd-fonts-symbols
