---
update: true

system_packages:
  - linux-headers
  - base
  - base-devel
  - linux
  - linux-firmware
  - netctl
  - networkmanager
  - openssh

  - pipewire
  - pipewire-alsa
  - pipewire-audio
  - pipewire-pulse
  - pipewire-jack
  - pavucontrol
  - wireplumber

  - nvidia-open
  - libva-nvidia-driver
  - nvidia-utils
  - lib32-nvidia-utils
  - nvidia-settings

  - egl-wayland

  - man-db
  - unzip
  - man-pages
  - reflector
  - mpv
  - mpv-mpris
  - git
  - wget
  - curl
  - udiskie
  - neovim
  - yazi

packages:
  - chaotic-aur/hyprland-git
  - cliphist
  - fuzzel
  - bemoji
  - waybar
  - xwaylandvideobridge
  - swww
  - dunst
  - polkit-kde-agent
  - qt5-wayland
  - qt6-wayland
  - chaotic-aur/xdg-desktop-portal-hyprland-git
  - xdg-desktop-portal-gtk
  - swappy
  - nwg-look

  - fd
  - tmux
  - fzf
  - ripgrep
  - zoxide
  - zsh
  - btop
  - starship
  - fastfetch

  - gtk3
  - catppuccin-gtk-theme-mocha
  - apple_cursor
  - papirus-icon-theme
  - gnome-themes-extra

# - zoom
  - spotify
  - steam
  - chaotic-aur/vesktop-git
  - librewolf
  - kitty
  - thunar

  - clang
  - python-pexpect

  - ttf-twemoji
  - ttf-symbola
  - noto-fonts
  - ttf-jetbrains-mono-nerd
  - ttf-jetbrains-mono
