---
- name: configure system
  hosts: all

  vars_prompt:
    - name: "user_password"
      prompt: "enter your password"
      private: yes

  vars_files:
    - config.yml

  tasks:
    - import_tasks: tasks/enable_multilib.yml
    - import_tasks: tasks/update.yml
    - import_tasks: tasks/system_packages.yml
    - import_tasks: tasks/chaotic_aur.yml
    - import_tasks: tasks/configure_nvidia.yml
    - import_tasks: tasks/sddm.yml
    - import_tasks: tasks/other_packages.yml
    - import_tasks: tasks/configure_zsh.yml
    - import_tasks: tasks/copy_dotfiles.yml
    - import_tasks: tasks/upgrade.yml
    - import_tasks: tasks/configure_xorg.yml
    - import_tasks: tasks/configure_tmux.yml
