---
- name: check if oh my zsh exists
  stat:
    path: ~/.oh-my-zsh
  register: omz_installed

- name: install oh my zsh
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"
  when: omz_installed.stat.exists == False

- name: check if zsh-autosuggestions exists
  stat:
    path: ~/.oh-my-zsh/plugins/zsh-autosuggestions
  register: zsh_autosuggestions

- name: install zsh-autosuggestions
  git:
    repo: "https://github.com/zsh-users/zsh-autosuggestions"
    dest: ~/.oh-my-zsh/plugins/zsh-autosuggestions
  when: zsh_autosuggestions.stat.exists == False

- name: check if zsh_syntax_highlighting exists
  stat:
    path: ~/.oh-my-zsh/plugins/zsh-syntax-highlighting
  register: zsh_syntax_highlighting

- name: install zsh_syntax_highlighting
  git:
    repo: "https://github.com/zsh-users/zsh-syntax-highlighting"
    dest: ~/.oh-my-zsh/plugins/zsh-syntax-highlighting
  when: zsh_syntax_highlighting.stat.exists == False

- name: check if fast_syntax_highlighting exists
  stat:
    path: ~/.oh-my-zsh/plugins/fast-syntax-highlighting
  register: fast_syntax_highlighting

- name: install fast_syntax_highlighting
  git:
    repo: "https://github.com/zdharma-continuum/fast-syntax-highlighting"
    dest: ~/.oh-my-zsh/plugins/fast-syntax-highlighting
  when: fast_syntax_highlighting.stat.exists == False

- name: check if colorize exists
  stat:
    path: ~/.oh-my-zsh/plugins/colorize
  register: colorize

- name: install colorize
  git:
    repo: "https://github.com/hsienjan/colorize"
    dest: ~/.oh-my-zsh/plugins/colorize
  when: colorize.stat.exists == False

- name: delete old zshrc
  file:
    path: ~/.zshrc
    state: absent

- name: copy zshrc
  copy:
    src: dotfiles/.zshrc
    dest: ~/.zshrc

- name: use zsh as the default shell
  expect:
    command: "chsh -s /usr/bin/zsh"
    responses:
      (?i)password: "{{ user_password }}"
    creates: ".shell_iz_zsh"
